create database Megaclass;
go

use Megaclass;
go

-- original table XXBCM_ORDER_MGT creation

CREATE TABLE XXBCM_ORDER_MGT 
   (	
	ORDER_REF 			VARCHAR(2000), 
	ORDER_DATE 			VARCHAR(2000), 
	SUPPLIER_NAME 		VARCHAR(2000), 
	SUPP_CONTACT_NAME 	VARCHAR(2000), 
	SUPP_ADDRESS 		VARCHAR(2000), 
	SUPP_CONTACT_NUMBER VARCHAR(2000), 
	SUPP_EMAIL 			VARCHAR(2000), 
	ORDER_TOTAL_AMOUNT 	VARCHAR(2000), 
	ORDER_DESCRIPTION 	VARCHAR(2000), 
	ORDER_STATUS 		VARCHAR(2000), 
	ORDER_LINE_AMOUNT 	VARCHAR(2000), 
	INVOICE_REFERENCE 	VARCHAR(2000), 
	INVOICE_DATE 		VARCHAR(2000), 
	INVOICE_STATUS 		VARCHAR(2000), 
	INVOICE_HOLD_REASON VARCHAR(2000), 
	INVOICE_AMOUNT 		VARCHAR(2000), 
	INVOICE_DESCRIPTION VARCHAR(2000)
   ) ;
go

-- original table XXBCM_ORDER_MGT data insertion
INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', '10000', 'Vehicle Spare parts', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-1', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Back lights', 'Received', '2500', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '2500', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-2', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Spark plug', 'Received', '600', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '600', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', '750000', 'Purchase of Car', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002-1', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Purchase of Car Model X', 'Received', '100000', 'INV_PO002.1', '01-MAR-2017', 'Paid', NULL, '100000', 'Part payment for purchase of car');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', '57300', 'Computer screens', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-1', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'Screens 22"', 'Received', '22000', 'INV_PO003.1', '22-MAR-2017', 'Paid', NULL, '22000', 'Purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-2', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'Screens 35"', 'Received', '20300', 'INV_PO003.1', '22-MAR-2017', 'Paid', NULL, '20300', 'Purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-3', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'Screens 15"', 'Received', '5000', 'INV_PO003.1', '22-MAR-2017', 'Paid', NULL, '5000', 'Purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-3', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Fuel filter', 'Received', '2000', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '2000', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', '6800', 'Purchase of Stationeries', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-1', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', NULL, 'Pen Parker blue', 'Received', '2000', 'INV_PO004', '15-FEB-2017', 'Paid', NULL, '2000', 'Payment for pen');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-2', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', NULL, 'Pencil HB boxes', 'Received', '2000', 'INV_PO004', '15-FEB-2017', 'Paid', NULL, '2000', 'Payment for pencil');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-4', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Air filter', 'Received', '800', 'INV_PO001', '28-FEB-2017', 'Paid', NULL, '800', 'Part payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002-2', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Purchase of Car Model X', 'Received', '300000', 'INV_PO002.2', '02-MAY-2017', 'Paid', NULL, '300000', 'Part payment for purchase of car');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698', 'mhem@my-t.mu', '21000', 'International Magazines', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-1', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698', 'mhem@my-t.mu', NULL, 'National geo nature', 'Received', '3000', 'INV_PO005.1', '18-MAY-2017', 'Pending', 'Damaged magazine', '3000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-2', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698', 'mhem@my-t.mu', NULL, 'Science world', 'Received', '5000', 'INV_PO005.1', '18-MAY-2017', 'Paid', NULL, '5000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO003-4', '24-JAN-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'Screens 35"', 'Received', '10000', 'INV_PO003.2', '15-MAY-2017', 'Paid', NULL, '10000', 'Final payment for purchase of screens.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO002-3', '10-JAN-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Purchase of Car Model X', 'Received', '249000', 'INV_PO002.3', '05-AUG-2017', 'Pending', NULL, '249000', 'Final payment for purchase of car');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-3', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', NULL, 'Paper reams', 'Received', '3000', 'INV_PO004.1', '20-MAR-2017', 'Paid', NULL, '3000', 'Paper reams.');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO004-4', '07-FEB-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', NULL, 'Clips boxes', 'Cancelled', '600', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-3', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698', 'mhem@my-t.mu', NULL, 'Science world', 'Received', '8000', 'INV_PO005.2', '22-JUN-2017', 'Paid', NULL, '8000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO005-4', '07-APR-2017', 'EMTELLO LTD', 'Megan Hembly', '998, Bistrop Street, Marlone, Pamplemousses, Mauritius', '2420641, 57841698', 'mhem@my-t.mu', NULL, 'Discovery mag', 'Received', '5000', 'INV_PO005.2', '22-JUN-2017', 'Paid', NULL, '5000', NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-5', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Brake disc', 'Received', '3000', 'INV_PO001.1', '04-APR-2017', 'Paid', NULL, '3000', 'Final payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO001-6', '03-JAN-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Axle', 'Received', '1100', 'INV_PO001.1', '04-APR-2017', 'Paid', NULL, '1100', 'Final payment for vehicle spare parts');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', '250000', 'Stationery orders', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-1', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 1', 'Received', '24300', 'INV_PO006.1', '22-MAR-2017', 'Paid', NULL, '24300', 'First delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 217 4512', 'steeve.nar@safedest.mu', '26700', 'Taxi services fees', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', '85200', 'Orders of computer spare parts', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-1', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 HDDs 3TB', 'Received', '30250', 'INV_PO008.1', '02-AUG-2017', 'Paid', NULL, '15250', 'Computer oders invoice - 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-2', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 Motherboard Asus PRIME Z270-A', 'Received', '48000', 'INV_PO008.1', '02-AUG-2017', 'Paid', NULL, '25000', 'Computer oders invoice - 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO009', '18-JUN-2017', 'FIRELAND BROS.', 'Amelia Bridney', '-, Main court bldg, Nerling road, Moka, Mauritius', '5948 0015', 'abridney@gmail.com', '36800', 'Security vests', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO009-1', '18-JUN-2017', 'FIRELAND BROS.', 'Amelia Bridney', '-, Main court bldg, Nerling road, Moka, Mauritius', '5948 0015', 'abridney@gmail.com', NULL, 'Security vests for firewardens', 'Received', '22500', 'INV_PO009.1', '24-AUG-2017', 'Paid', NULL, '22500', 'Security vests');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', '182700', 'Electronic spare parts', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-1', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Electronic Component Lead 2000 Kgs', 'Received', '98000', 'INV_PO010.1', '15-AUG-2017', 'Paid', NULL, '98000', 'Electronic spare parts - Inv 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-2', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Air Conditioner Fan Capacitor x 1000', 'Received', '17500', 'INV_PO010.1', '15-AUG-2017', 'Paid', NULL, '17500', 'Electronic spare parts - Inv 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-3', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Aluminium LED PCB Assemblies x 100', 'Received', '28000', 'INV_PO010.1', '02-SEP-2017', 'Paid', NULL, '28000', 'Electronic spare parts - Inv 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-4', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Starter capacitor x 2000', 'Received', '18200', 'INV_PO010.1', '02-SEP-2017', 'Paid', NULL, '18200', 'Electronic spare parts - Inv 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO010-5', '03-JUL-2017', 'FOXY ELECTRONICS', 'Reddy Floyd', 'C47, Green Street, -, Savanne, Mauritius', '5284 5412', 'foxyelec@yahoo.fr', NULL, 'Block connector universal x 200', 'Received', '21000', 'INV_PO010.1', '15-AUG-2017', 'Paid', NULL, '21000', 'Electronic spare parts - Inv 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO011', '06-JUL-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', '43200', 'Purchase of Stationeries', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO011-1', '06-JUL-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', NULL, 'Staplers Heavy duty x 10', 'Received', '3200', 'INV_PO011.1', '18-SEP-2017', 'Paid', NULL, '3200', 'Stationeries');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-3', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 HDDs 3TB', 'Received', '30250', 'INV_PO008.2', '28-AUG-2017', 'Paid', NULL, '15000', 'Computer oders invoice - 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-4', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, '10 Motherboard Asus PRIME Z270-A', 'Received', '48000', 'INV_PO008.2', '28-AUG-2017', 'Paid', NULL, '23000', 'Computer oders invoice - 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-2', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 3', 'Received', '25400', 'INV_PO006.3', '21-MAY-2017', 'Paid', NULL, '25400', 'Third delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO011-2', '06-JUL-2017', 'LAMBONI STAT INC.', 'Frederic Pey', '9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses', '52557435', 'manustat@gmail.com', NULL, 'Organizers x 200', 'Received', '40000', 'INV_PO011.1', '18-SEP-2017', 'Paid', NULL, '40000', 'Stationeries');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', '265000', 'Vehicle Spare parts', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-1', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Aluminium evaporator x 15', 'Received', '3450', 'INV_PO012.1', '07-AUG-2017', 'Paid', NULL, '3450', 'Vehicle spare parts - Part Pay 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-3', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 4', 'Received', '50200', 'INV_PO006.4', '17-JUN-2017', 'Paid', NULL, '50200', 'Fourth delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO008-5', '05-JUN-2017', 'JINFIX COMPUTERS', 'Jordan Liu Min', '93, Bardeau lane, - , Port Louis, Mauritius', '58412556,2195412', 'contactus@jinfixcomputers.com', NULL, 'Seagate Barracuda 2TB SATA Hard Drive', 'Received', '6950', 'INV_PO008.2', '28-AUG-2017', 'Paid', NULL, '6950', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-2', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Wheels and balancing', 'Received', '40000', 'INV_PO012.2', '04-SEP-2017', 'Paid', NULL, '40000', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-3', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Servicing of cars', 'Received', '37800', 'INV_PO012.1', '07-AUG-2017', 'Paid', NULL, '37800', 'Vehicle spare parts - Part Pay 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-4', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Dashboard for cards', 'Received', '12500', 'INV_PO012.2', '04-SEP-2017', 'Paid', NULL, '12500', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-5', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Rear door + repair', 'Received', '28000', 'INV_PO012.3', '29-SEP-2017', 'Paid', NULL, '28000', 'Vehicle spare parts - Part Pay 3');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-6', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'High pressure fuel injector nozzle OEM x 10', 'Received', '7250', 'INV_PO012.1', '07-AUG-2017', 'Paid', NULL, '7250', 'Vehicle spare parts - Part Pay 1');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-7', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Air suspension compressor x 3', 'Received', '55870', 'INV_PO012.2', '04-SEP-2017', 'Paid', NULL, '55870', 'Vehicle spare parts - Part Pay 2');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-8', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Aluminium alloy set x 5', 'Received', '43750', 'INV_PO012.3', '29-SEP-2017', 'Paid', NULL, '43750', 'Vehicle spare parts - Part Pay 3');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO012-9', '16-AUG-2017', 'PEGASUS LTD', 'Georges Neeroo', '40, Ferney Way, Mission Road, Curepipe, Mauritius', '461 5841, 57412545', 'geonee@pegasus.mu', NULL, 'Master brake x 12', 'Received', '12600', 'INV_PO012.3', '29-SEP-2017', 'Paid', NULL, '12600', 'Vehicle spare parts - Part Pay 3');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-4', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 5', 'Received', '70800', 'INV_PO006.5', '27-JUL-2017', 'Paid', NULL, '70800', 'Fifth delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', '5819625', 'Purchase of Cars', 'Closed', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-1', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Audi Q5', 'Received', '1452500', 'INV_PO013.1', '28-SEP-2017', 'Paid', NULL, '1452500', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-2', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Audi Q7', 'Received', '1974000', 'INV_PO013.1', '28-SEP-2017', 'Paid', NULL, '1974000', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-3', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Chevrolet Equinox', 'Received', '1302000', 'INV_PO013.1', '28-SEP-2017', 'Paid', NULL, '1302000', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO013-4', '20-AUG-2017', 'MOTTOWAY CORP.', 'Stevens Seernah', 'B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius', '5794 2513', 'steseer@mottoway.com', NULL, 'Hyundai Tucson', 'Received', '1091125', 'INV_PO013.1', '28-SEP-2017', 'Paid', NULL, '1091125', 'Car purchase');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-5', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 6', 'Received', '60000', 'INV_PO006.6', '16-AUG-2017', 'Paid', NULL, '60000', 'Sixth delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-1', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 217 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '4500', 'INV_PO007.1', '30-JUL-2017', 'Paid', NULL, '4500', 'Trip for Saunders');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-2', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 217 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '4200', 'INV_PO007.1', '30-JUL-2017', 'Paid', NULL, '4200', 'Trip for Mike');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-3', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 217 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Cancelled', '5200', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-4', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 217 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '4800', 'INV_PO007.1', '30-JUL-2017', 'Paid', NULL, '4800', 'Trip for Shobnee');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO007-5', '03-JUN-2017', 'SAFEDEST TAXI SERVICES', 'Steeve Narsimullu', '-, Le clezio street, Barbley wood, Highlands, Mauritius', '5874 1002, 217 4512', 'steeve.nar@safedest.mu', NULL, 'Employee journey taxi service', 'Received', '3700', 'INV_PO007.1', '30-JUL-2017', 'Paid', NULL, '3700', 'Trip for Mikaen');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO006-6', '16-FEB-2017', 'STUFFIE STATIONERY', 'Zenhir Belall', '67, Bistro Route, Heneral Street, Vacaoas, Mauritius', '6547416', 'info@sstat.com', NULL, 'Packet 2', 'Received', '4300', 'INV_PO006.2', '18-APR-2017', 'Paid', NULL, '4300', 'Second delivery');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', '400120', 'Purchases of Digital equipment', 'Open', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-1', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, '2.5 EXTERNAL TOSHIBA 1TB HARD DISK USB 3.0 x 2', 'Received', '5600', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '5600', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-2', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, '2.5 EXTERNAL TOSHIBA 2TB HARD DISK USB 3.0 x 3', 'Received', '13250', 'INV_PO014.2', '15-OCT-2017', 'Paid', NULL, '13250', 'Invoice payment SN#002');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-3', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'NOTEBOOK SATA HDD - 500 GB x 5', 'Received', '10000', 'INV_PO014.2', '15-OCT-2017', 'Paid', NULL, '10000', 'Invoice payment SN#002');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-4', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, '3TB SATA HARD DISK x 4', 'Received', '15900', 'INV_PO014.3', '27-OCT-2017', 'Paid', NULL, '15900', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-5', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'WESTERN DIGITAL USB 3.0 EXTERNAL HARD DISK 3.5 4TB x 2', 'Received', '13850', 'INV_PO014.4', '05-NOV-2017', 'Pending', '1 faulty HD to return before payment', '13850', 'Invoice payment SN#004');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-6', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'FAN UNIT x 20', 'Cancelled', '800', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-7', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'EPSON EB-S31 3LCD PROJECTOR x 3', 'Received', '54850', 'INV_PO014.3', '27-OCT-2017', 'Paid', NULL, '54850', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-8', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'VIEWSONIC PJD5155 PROJECTOR', 'Received', '17300', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '17300', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-9', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'COOLER MASTER SEIDON120V V3 PLUS WATER-COOLING KIT x 5', 'Received', '13500', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '13500', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-10', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'GENIUS MEDIA POINTER 900BT x 3', 'Received', '4275', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '4275', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-11', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'USB WIRELESS <<T>> LASER POINTER PRESENTER x 2', 'Received', '900', 'INV_PO014.3', '27-OCT-2017', 'Pending', 'Pointers not compatible with system', '900', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-12', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'ASUS H110M-A (INTEL H110) DDR4 LGA1151 MATX x 4', 'Received', '17600', 'INV_PO014.4', '05-NOV-2017', 'Paid', NULL, '17600', 'Invoice payment SN#004');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-13', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'ASUS B150M-K DDR4 (INTEL B150) LGA1151 MATX x 2', 'Received', '11900', 'INV_PO014.4', '05-NOV-2017', 'Paid', NULL, '11900', 'Invoice payment SN#004');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-14', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'ASUS H81M-A (INTEL H81) LGA1150 MATX x 2', 'Received', '7920', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '7920', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-15', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'HP ADVANTAGE 4535 ALL-IN-ONE INKJET PRINTER', 'Received', '3550', 'INV_PO014.2', '15-OCT-2017', 'Pending', NULL, '3550', 'Invoice payment SN#002');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-16', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'HP M277DW WIFI COLOUR LASERJET PRO MFP', 'Received', '15200', 'INV_PO014.1', '03-OCT-2017', 'Paid', NULL, '15200', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-17', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'HP OFFICEJET PRO 6830 E-ALL-IN-ONE PRINTER', 'Received', '5300', 'INV_PO014.3', '27-OCT-2017', 'Paid', NULL, '5300', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-18', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'EPSON LQ310 DOT MATRIX PRINTER', 'Received', '12125', 'INV_PO014.3', '27-OCT-2017', 'Paid', NULL, '12125', 'Invoice payment SN#003');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-19', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'LENOVO B50-30 x 5', 'Received', '72500', 'INV_PO014.1', '03-OCT-2017', 'Pending', NULL, '72500', 'Invoice payment SN#001');

INSERT INTO XXBCM_ORDER_MGT (ORDER_REF, ORDER_DATE, SUPPLIER_NAME, SUPP_CONTACT_NAME, SUPP_ADDRESS, SUPP_CONTACT_NUMBER, SUPP_EMAIL, ORDER_TOTAL_AMOUNT, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT, INVOICE_REFERENCE, INVOICE_DATE, INVOICE_STATUS, INVOICE_HOLD_REASON, INVOICE_AMOUNT, INVOICE_DESCRIPTION) 
VALUES ('PO014-20', '15-SEP-2017', 'DIGISAY CO. LTD.', 'Berry Parker', '68, Marock Lane, - , Vacoas, Mauritius', '57841266, 6028010', 'bparker@intnet.mu', NULL, 'DELL N3543 CORE i5 x 3', 'Cancelled', '103800', NULL, NULL, NULL, NULL, NULL, NULL);


go
create table Supplier(
supplier_reference int identity primary key,
supplier_name varchar(40) not null,
Supplier_contactname varchar(40) not null,
Supplier_address varchar(200) not null,
Supplier_contactnumber1 varchar(20) not null,
Supplier_contactnumber2 varchar(20),
Supplier_email varchar(40) not null);

go

create table Orders(
order_reference varchar(10) primary key, 
supplier_reference int not null,
order_date date not null,
Order_totalamount int not null,
Order_description varchar(80) not null,
Order_status varchar(20) not null,
foreign key(supplier_reference) references Supplier(supplier_reference));

go


create table Order_line(
order_reference varchar(10) not null, 
order_line_reference int not null,
Order_line_amount int not null,
primary key(order_reference, order_line_reference),
foreign key(order_reference) references Orders(order_reference));

go


create table Invoice(
Invoice_reference varchar(20) ,
order_reference  varchar(10) not null,
order_line_reference int not null,
Invoice_date date not null,
Invoice_status varchar(20) not null,
Invoice_hold_reason varchar(200),
Invoice_amount int not null,
Invoice_description varchar(200),
primary key(Invoice_reference, order_reference, order_line_reference),
foreign key(order_reference, order_line_reference) references Order_line(order_reference, order_line_reference));

go